apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-router
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - adrioliveira.cf
    - www.adrioliveira.cf
    secretName: letsencrypt-prod
  rules:
  - host: adrioliveira.cf
    http: 
      paths:
        - backend:
            serviceName: hello-world-svc
            servicePort: 8080
  - host: www.adrioliveira.cf
    http: 
      paths:
        - backend:
            serviceName: hello-world-svc
            servicePort: 8080
          

