apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins
spec:
  ports:
    - name: jenkins-ui
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: jenkins