apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app: hello-world-svc
    duration: temporary
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-world
    duration: temporary
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
    duration: temporary
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 3
  selector:
    matchLabels:
      app: hello-world
      duration: temporary
  template:
    metadata:
      labels:
        app: hello-world
        duration: temporary
    spec:
      restartPolicy: Always
      containers:
      - name: hello-world
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

